### PR TITLE
fa: make the code compile with gcc-10.2.1

### PR DESCRIPTION
**Pull request by kdudka**
This commit fixes the following warnings and errors:
```
Error: COMPILER_WARNING:
fa/compiler.cc: scope_hint: At global scope
fa/compiler.cc:157:13: warning[-Wunused-function]: ‘std::string {anonymous}::translOperandCode(unsigned int)’ defined but not used

Error: COMPILER_WARNING:
fa/fixpoint.cc: scope_hint: At global scope
fa/fixpoint.cc:324:6: warning[-Wunused-function]: ‘void {anonymous}::getCandidates(std::set<long unsigned int>&, const FAE&)’ defined but not used

Error: COMPILER_WARNING:
fa/folding.cc: scope_hint: At global scope
fa/folding.cc:137:6: warning[-Wunused-function]: ‘bool {anonymous}::isSignaturesCompatible(const CutpointSignature&, const CutpointSignature&)’ defined but not used

Error: COMPILER_WARNING:
fa/folding.cc: scope_hint: In member function ‘bool Folding::discover1(size_t, const std::set<long unsigned int>&, bool)’
fa/folding.cc:300:10: error: converting to ‘bool’ from ‘std::nullptr_t’ requires direct-initialization [-fpermissive]

Error: COMPILER_WARNING:
fa/folding.cc: scope_hint: In member function ‘bool Folding::discover2(size_t, const std::set<long unsigned int>&, bool)’
fa/folding.cc:356:10: error: converting to ‘bool’ from ‘std::nullptr_t’ requires direct-initialization [-fpermissive]

Error: COMPILER_WARNING:
fa/folding.cc: scope_hint: In member function ‘bool Folding::discover3(size_t, const std::set<long unsigned int>&, bool)’
fa/folding.cc:431:10: error: converting to ‘bool’ from ‘std::nullptr_t’ requires direct-initialization [-fpermissive]

Error: COMPILER_WARNING:
fa/forestaut.cc:27:8: warning[-Wunused-function]: ‘size_t {anonymous}::getLabelArity(std::vector<const AbstractBox*>&)’ defined but not used

Error: COMPILER_WARNING:
fa/programconfig.cc: scope_hint: In member function ‘void ProgramConfig::processArg(const string&)’
fa/programconfig.cc:30:7: error: ‘vector’ is not a member of ‘std’
fa/programconfig.cc:22:1: note: ‘std::vector’ is defined in header ‘<vector>’; did you forget to ‘#include <vector>’?

Error: COMPILER_WARNING:
fa/programconfig.cc:30:20: error: expected primary-expression before ‘>’ token

Error: COMPILER_WARNING:
fa/programconfig.cc:30:22: error: ‘data’ was not declared in this scope

Error: COMPILER_WARNING:
fa/cl_fa.cc:31: included_from: Included from here.
fa/programconfig.hh: scope_hint: In constructor ‘ProgramConfig::ProgramConfig(const string&)’
fa/programconfig.hh:54:8: error: ‘vector’ is not a member of ‘std’
fa/programconfig.hh:28:1: note: ‘std::vector’ is defined in header ‘<vector>’; did you forget to ‘#include <vector>’?

Error: COMPILER_WARNING:
fa/programconfig.hh:54:26: error: expected primary-expression before ‘>’ token

Error: COMPILER_WARNING:
fa/programconfig.hh:54:28: error: ‘args’ was not declared in this scope

Error: COMPILER_WARNING:
fa/symctx.hh:34: included_from: Included from here.
fa/compiler.cc:40: included_from: Included from here.
fa/symctx.hh: scope_hint: In constructor ‘SymCtx::SymCtx(const CodeStorage::Fnc&, const var_map_type*)’
fa/streams.hh:55:11: error: converting to ‘bool’ from ‘std::nullptr_t’ requires direct-initialization [-fpermissive]
fa/streams.hh:93:2: note: in expansion of macro ‘FA_MSG_STREAM’
fa/streams.hh:124:2: note: in expansion of macro ‘FA_MSG_STREAM_INTERNAL’
fa/symctx.hh:224:7: note: in expansion of macro ‘FA_NOTE’
```

### CODE REVIEW

**Comment by kdudka** [comment]
I am merging this just in case someone needed the build fix later on.  Forester is going to be removed from this repository because its development was moved elsewhere long time ago.  See http://www.fit.vutbr.cz/research/groups/verifit/tools/forester/ for details.
